// khronos.glesv1 — libGLESv1_CM, as a C++23 module.
//
// A module wrapper and nothing more: every name below is upstream's, spelled
// upstream's way. `import khronos.glesv1;` replaces `#include <GLES/gl.h>`
// and changes nothing else.
//
// GENERATED by mcpp/tools/genglmod.sh from <GLES/gl.h> INTERSECTED with the
// symbols libGLESv1_CM.so actually defines — 145 declared, 145 defined,
// 145 exported here. The intersection is the point: a header can declare more
// than its library dispatches, and exporting a name that does not link would
// turn a version skew into an error in the user's build rather than in ours.
//
// WHAT IS NOT HERE
//
// * The GL_* CONSTANTS. They are macros, and a module cannot export a macro —
//   `export` names entities. Include <GLES/gl.h> alongside the import when you
//   need GL_COLOR_BUFFER_BIT or GL_TRIANGLES; it is the same header this was
//   generated from, so nothing disagrees.
// * EXTENSIONS. <GLES/…ext.h> is a separate header and its entry points
//   are resolved through eglGetProcAddress at runtime, not linked.
module;



#include <GLES/gl.h>

export module khronos.glesv1;

export {

// -- types --
using ::GLbitfield;
using ::GLboolean;
using ::GLbyte;
using ::GLclampf;
using ::GLclampx;
using ::GLenum;
using ::GLfixed;
using ::GLfloat;
using ::GLint;
using ::GLintptr;
using ::GLshort;
using ::GLsizei;
using ::GLsizeiptr;
using ::GLubyte;
using ::GLuint;
using ::GLushort;
using ::GLvoid;

// -- entry points --
using ::glActiveTexture;
using ::glAlphaFunc;
using ::glAlphaFuncx;
using ::glBindBuffer;
using ::glBindTexture;
using ::glBlendFunc;
using ::glBufferData;
using ::glBufferSubData;
using ::glClear;
using ::glClearColor;
using ::glClearColorx;
using ::glClearDepthf;
using ::glClearDepthx;
using ::glClearStencil;
using ::glClientActiveTexture;
using ::glClipPlanef;
using ::glClipPlanex;
using ::glColor4f;
using ::glColor4ub;
using ::glColor4x;
using ::glColorMask;
using ::glColorPointer;
using ::glCompressedTexImage2D;
using ::glCompressedTexSubImage2D;
using ::glCopyTexImage2D;
using ::glCopyTexSubImage2D;
using ::glCullFace;
using ::glDeleteBuffers;
using ::glDeleteTextures;
using ::glDepthFunc;
using ::glDepthMask;
using ::glDepthRangef;
using ::glDepthRangex;
using ::glDisable;
using ::glDisableClientState;
using ::glDrawArrays;
using ::glDrawElements;
using ::glEnable;
using ::glEnableClientState;
using ::glFinish;
using ::glFlush;
using ::glFogf;
using ::glFogfv;
using ::glFogx;
using ::glFogxv;
using ::glFrontFace;
using ::glFrustumf;
using ::glFrustumx;
using ::glGenBuffers;
using ::glGenTextures;
using ::glGetBooleanv;
using ::glGetBufferParameteriv;
using ::glGetClipPlanef;
using ::glGetClipPlanex;
using ::glGetError;
using ::glGetFixedv;
using ::glGetFloatv;
using ::glGetIntegerv;
using ::glGetLightfv;
using ::glGetLightxv;
using ::glGetMaterialfv;
using ::glGetMaterialxv;
using ::glGetPointerv;
using ::glGetString;
using ::glGetTexEnvfv;
using ::glGetTexEnviv;
using ::glGetTexEnvxv;
using ::glGetTexParameterfv;
using ::glGetTexParameteriv;
using ::glGetTexParameterxv;
using ::glHint;
using ::glIsBuffer;
using ::glIsEnabled;
using ::glIsTexture;
using ::glLightf;
using ::glLightfv;
using ::glLightModelf;
using ::glLightModelfv;
using ::glLightModelx;
using ::glLightModelxv;
using ::glLightx;
using ::glLightxv;
using ::glLineWidth;
using ::glLineWidthx;
using ::glLoadIdentity;
using ::glLoadMatrixf;
using ::glLoadMatrixx;
using ::glLogicOp;
using ::glMaterialf;
using ::glMaterialfv;
using ::glMaterialx;
using ::glMaterialxv;
using ::glMatrixMode;
using ::glMultiTexCoord4f;
using ::glMultiTexCoord4x;
using ::glMultMatrixf;
using ::glMultMatrixx;
using ::glNormal3f;
using ::glNormal3x;
using ::glNormalPointer;
using ::glOrthof;
using ::glOrthox;
using ::glPixelStorei;
using ::glPointParameterf;
using ::glPointParameterfv;
using ::glPointParameterx;
using ::glPointParameterxv;
using ::glPointSize;
using ::glPointSizePointerOES;
using ::glPointSizex;
using ::glPolygonOffset;
using ::glPolygonOffsetx;
using ::glPopMatrix;
using ::glPushMatrix;
using ::glReadPixels;
using ::glRotatef;
using ::glRotatex;
using ::glSampleCoverage;
using ::glSampleCoveragex;
using ::glScalef;
using ::glScalex;
using ::glScissor;
using ::glShadeModel;
using ::glStencilFunc;
using ::glStencilMask;
using ::glStencilOp;
using ::glTexCoordPointer;
using ::glTexEnvf;
using ::glTexEnvfv;
using ::glTexEnvi;
using ::glTexEnviv;
using ::glTexEnvx;
using ::glTexEnvxv;
using ::glTexImage2D;
using ::glTexParameterf;
using ::glTexParameterfv;
using ::glTexParameteri;
using ::glTexParameteriv;
using ::glTexParameterx;
using ::glTexParameterxv;
using ::glTexSubImage2D;
using ::glTranslatef;
using ::glTranslatex;
using ::glVertexPointer;
using ::glViewport;

} // export
