#!/bin/sh
#
# Generate the C++23 module wrapper for one GL library.
#
# WHY A GENERATOR AND NOT A HAND-WRITTEN LIST
#
# The export list must not be able to drift from the library. Hand-maintained,
# a version bump that adds an entry point leaves it unexported and nobody
# notices; one that REMOVES an entry point leaves a `using ::name;` that no
# longer resolves and the module stops compiling for a reason that reads like a
# toolchain bug. Generated from the header, neither can happen quietly, and CI
# regenerates and diffs.
#
# WHY THE INTERSECTION WITH THE BUILT LIBRARY
#
# A header can declare more than its library defines — `GL/glcorearb.h`
# declares 1278 entry points and `libOpenGL.so.0` exports 1044, because the
# header is the whole registry and the library is what GLVND dispatches. The
# module exports the INTERSECTION, so every exported name is one that actually
# links. Without this, `import khronos.opengl;` would compile and then fail at
# link time on a name the user never typed.
#
# WHY sh AND NOT PYTHON
#
# The libglvnd fork already keeps Python off the build path (mcpp/generated/ is
# checked in, and the only Python left runs in CI as a drift guard). This is
# text extraction over two files; sh + sed + comm does it without adding a
# second language to the same job.
#
# Usage: mcpp/tools/genglmod.sh <flavour> <header> <library.so> <output.cppm>
#   e.g. genglmod.sh glesv2 GLES3/gl32.h <path>/libGLESv2.so mcpp/glesv2/src/glesv2.cppm
set -eu

# LC_ALL=C, and this is not cosmetic. `sort` orders mixed-case identifiers
# differently under a UTF-8 locale than under C, so the same inputs produce a
# different FILE on a developer machine than on a CI runner — same symbol
# count, different order, and the drift check fails with a diff that looks like
# nothing changed. Measured: 48 lines of glesv2.cppm.
export LC_ALL=C

FLAVOUR="$1"      # glesv2 | glesv1 | opengl
HEADER="$2"       # header path RELATIVE to upstream/include
LIB="$3"          # the built .so, for the intersection
OUT="$4"

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
INC="$ROOT/upstream/include"

[ -f "$INC/$HEADER" ] || { echo "no such header: $INC/$HEADER" >&2; exit 1; }
[ -f "$LIB" ]         || { echo "no such library: $LIB (build it first)" >&2; exit 1; }

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# Declared entry points. The three spellings upstream uses for "this is an API
# function": GL_APICALL (GLES2/3), GL_API (GLES1), GLAPI (desktop GL).
sed -n 's/^\(GL_APICALL\|GL_API\|GLAPI\) .* \**\(gl[A-Za-z0-9_]*\) *(.*/\2/p' \
    "$INC/$HEADER" | sort -u > "$tmp/declared"

# What the library actually defines.
readelf --dyn-syms -W "$LIB" \
    | awk '$4 == "FUNC" && $5 == "GLOBAL" { print $8 }' \
    | sed 's/@.*//' | grep '^gl' | sort -u > "$tmp/defined"

comm -12 "$tmp/declared" "$tmp/defined" > "$tmp/funcs"

# Types. GL's are all `typedef … GLxxx;` one-liners in the platform headers;
# taking them from the umbrella header's include closure would drag in libc, so
# the list is the GL* typedefs the header itself names.
sed -n 's/^typedef .* \**\(GL[A-Za-z0-9_]*\);.*/\1/p' "$INC/$HEADER" | sort -u > "$tmp/types"

nf=$(wc -l < "$tmp/funcs"); nt=$(wc -l < "$tmp/types")
nd=$(wc -l < "$tmp/declared"); nD=$(wc -l < "$tmp/defined")

# Some headers hide their prototypes behind GL_GLEXT_PROTOTYPES and declare
# only function-pointer typedefs otherwise — GL/glcorearb.h does, GLES3/gl32.h
# and GLES/gl.h do not. Detected rather than special-cased: the extraction
# above is plain text and sees the declarations either way, but the COMPILER
# needs the macro or every `using ::glFoo;` fails with "has not been declared".
PROTOS=""
if grep -q '^#ifdef GL_GLEXT_PROTOTYPES' "$INC/$HEADER"; then
    PROTOS="#define GL_GLEXT_PROTOTYPES 1"
fi

{
cat <<HEAD
// khronos.$FLAVOUR — $(basename "$LIB" | sed 's/\.so$//'), as a C++23 module.
//
// A module wrapper and nothing more: every name below is upstream's, spelled
// upstream's way. \`import khronos.$FLAVOUR;\` replaces \`#include <$HEADER>\`
// and changes nothing else.
//
// GENERATED by mcpp/tools/genglmod.sh from <$HEADER> INTERSECTED with the
// symbols $(basename "$LIB") actually defines — $nd declared, $nD defined,
// $nf exported here. The intersection is the point: a header can declare more
// than its library dispatches, and exporting a name that does not link would
// turn a version skew into an error in the user's build rather than in ours.
//
// WHAT IS NOT HERE
//
// * The GL_* CONSTANTS. They are macros, and a module cannot export a macro —
//   \`export\` names entities. Include <$HEADER> alongside the import when you
//   need GL_COLOR_BUFFER_BIT or GL_TRIANGLES; it is the same header this was
//   generated from, so nothing disagrees.
// * EXTENSIONS. <${HEADER%/*}/…ext.h> is a separate header and its entry points
//   are resolved through eglGetProcAddress at runtime, not linked.
module;

$PROTOS

#include <$HEADER>

export module khronos.$FLAVOUR;

export {

// -- types --
HEAD
sed 's/^/using ::/; s/$/;/' "$tmp/types"
printf '\n// -- entry points --\n'
sed 's/^/using ::/; s/$/;/' "$tmp/funcs"
printf '\n} // export\n'
} > "$OUT"

echo "$FLAVOUR: $nf entry points + $nt types  ($nd declared, $nD defined)"
